version: '3.9'
services:
  ironman:
    build:
      context: ./py-app
      dockerfile: Dockerfile.py-app
    environment:
      - PORT=8081
    expose:
      - 8081
    

  falcon:
    build:
      context: ./express-app
      dockerfile: Dockerfile.express-app
    environment:
      - PORT=8082 
    expose:
      - 8082

    
    
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    
    ports:
      - 8080:80
    depends_on:
      - ironman
      - falcon
    